### ISSUE TITLE
Placeholder Create Recipe Form

### ISSUE THREAD

**Issue by mab5vot9us9a** [open-eats/openeats-web#25]
Hi,
Today I installed OpenEats using docker according to [these instructions](https://github.com/open-eats/OpenEats/blob/master/docs/Running_the_App.md) with no specific version supplied to the `quick-start.py` command, so it should have pulled the latest version.

Upon creating my first recipe, I noticed that the placeholder image in the create recipe form could not be loaded. The issue appears to be a wrong file extension. According to the Chrome DevTools Network tab, the site tries to load `/images/fried-eggs.png`, which is not available. However, `/images/fried-eggs.jpg` is available.

![screenshot 2019-01-03 at 17 13 00](https://user-images.githubusercontent.com/8020703/50648724-3620ee80-0f7c-11e9-90cd-cc8caa62bcbe.png)

![screenshot 2019-01-03 at 17 17 15](https://user-images.githubusercontent.com/8020703/50648723-35885800-0f7c-11e9-9620-614441981c8d.png)

**Comment by RyanNoelk** [comment]
Good catch. I'll fix this up in a small patch.

**Comment by RyanNoelk** [comment]
Fixed in: https://github.com/open-eats/openeats-web/pull/28
