### ISSUE TITLE
Django Admin Interface News Typo

### ISSUE THREAD

**Issue by mab5vot9us9a** [open-eats/openeats-web#26]
I noticed a typo in the Django Admin Interface under the News category, where News is written like this: "Newss".

![screenshot 2019-01-03 at 17 24 42](https://user-images.githubusercontent.com/8020703/50648877-ae87af80-0f7c-11e9-9bd5-945b361c5c30.png)

**Comment by RyanNoelk** [comment]
👍 Will fix this soon.

**Comment by RyanNoelk** [comment]
Fixed in: https://github.com/open-eats/openeats-api/pull/26
