### ISSUE TITLE
Quantity is disappearing on preview

### ISSUE THREAD

**Issue by tekand** [open-eats/openeats-web#46]
Enter quantity for an ingredient (either by creating a new recipe or editing an old one):
![image](https://user-images.githubusercontent.com/8311914/81760071-2e7c2e80-947b-11ea-861e-5eff234ba6bf.png)

Click on Preview:
![image](https://user-images.githubusercontent.com/8311914/81760084-35a33c80-947b-11ea-9d5c-a08c0a383cd0.png)

The cause is that the ingredient object does not have `quantity` attribute.
![image](https://user-images.githubusercontent.com/8311914/81760208-7ef38c00-947b-11ea-80bd-7344a60e42e6.png)

Seems like a side effect of #8 . How did it work for everybody in the last two years?
On the demo page it seems to work, because it still has a pre #8 version.

**Comment by RyanNoelk** [comment]
Thanks for the Report. I've fixed this issue in #48
