### ISSUE TITLE
Add Youtube videos

### ISSUE THREAD

**Issue by rpanchon** [open-eats/openeats-web#49]
First of all. Congratulations for your project.
I'm using it from a few days ago, and I want to know if, you have in mind the possibility to add youtube videos in the directions. 
Doing something like the ":" at the end of the line to put in bold the instruction.
Thank you so much.

**Comment by RyanNoelk** [comment]
I do not want to include embedding YouTube videos within the app. YouTube can bring in some nasty cookies/tracking js that I don't want in the app.

For adding direction sections see: https://github.com/open-eats/OpenEats/issues/125
